---
title: "Lab_6_Warmup"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Load data 
```{r}
getwd()
```


```{r}
library("tidyverse")
```

```{r}
bison <- readr :: read_csv("data/bison.csv")
bison
```
## 2. Dimensions and structure of data
```{r}
dim(bison)
```

```{r}
str(bison)
```

```{r}
names(bison)
```

## 3. Select certain variables
```{r}
bison2<- bison %>% 
  select("animal_code", "animal_sex", "animal_weight", "animal_yob")

```

## 4. Pull out animals born in 1980-1990
```{r}
bison2 %>% 
  filter(animal_yob >= 1980 & animal_yob <= 1990)
```

## 5. Compare how many male or female bison are represented between 1980 and 1990
```{r}
bison_f <- filter(bison2, animal_sex == "F")
bison_f
```

```{r}
summary(bison_f)
```


```{r}
bison_m <- filter(bison2, animal_sex == "M")
bison_m
```

```{r}
summary(bison_m)
```
# other way of doing the same 
```{r}
bison_m <- bison2 %>% 
  filter(animal_yob >= 1980 & animal_yob <= 1990) %>% 
  filter(animal_sex == "M")
bison_m
```

```{r}
bison_f <- bison2 %>% 
  filter(animal_yob >= 1980 & animal_yob <= 1990) %>% 
  filter(animal_sex == "F")
bison_f
```


## 6. Who were larger on average, females or males?
```{r}
mean(bison_m$animal_weight)
```

```{r}
mean(bison_f$animal_weight)
```

